### PR TITLE
Update to official CNCF logo and link to homepage

### PR DESCRIPTION
**Pull request by robszumski**
Use official CNCF white logo (https://branding.cncf.io/projects/operatorframework/) and link to OF homepage to match CNCF/LF logo guidelines.

### CODE REVIEW

**Review by jozzi — APPROVED** [review]

**Comment by jozzi** [comment]
@robszumski I am not able to merge it as do not have those rights anymore so either you can do so or someone else :)

**Comment by robszumski** [comment]
@jozzi any ideas on the build error?

**Comment by jozzi** [comment]
From what I have seen it fails before actual build  when logging to docker. No idea why or what could have changed.

**Comment by Edke** [comment]
Hi @robszumski, I spent few days debugging docker login and why build failed and I have to admit have no idea why build failed. Tried that today to prepare new MR from branch and force to rebuild ... and it works ! Sometimes Travis is  tricky and does strange things ! Is this PR final ? In case, let's try to merge it.

**Comment by robszumski** [comment]
Thanks for the update. I'll go ahead and merge it.

**Pull request merged**
